# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/catgray/catgray/code/CatLearnQt/examples/QCatGrayWidgetExamples/WidgetTools/SliderTools.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SliderTools(object):
    def setupUi(self, SliderTools):
        SliderTools.setObjectName("SliderTools")
        SliderTools.resize(600, 435)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SliderTools)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(125, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.scrollArea = QtWidgets.QScrollArea(SliderTools)
        self.scrollArea.setMinimumSize(QtCore.QSize(310, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 308, 411))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SliderWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.SliderWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.SliderWidget.setObjectName("SliderWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SliderWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Define = QtWidgets.QLabel(self.SliderWidget)
        self.Define.setAlignment(QtCore.Qt.AlignCenter)
        self.Define.setObjectName("Define")
        self.verticalLayout_3.addWidget(self.Define)
        self.SilderVbLayout = QtWidgets.QVBoxLayout()
        self.SilderVbLayout.setContentsMargins(-1, 10, -1, 10)
        self.SilderVbLayout.setSpacing(5)
        self.SilderVbLayout.setObjectName("SilderVbLayout")
        self.verticalLayout_3.addLayout(self.SilderVbLayout)
        self.SilderHbLayout = QtWidgets.QHBoxLayout()
        self.SilderHbLayout.setContentsMargins(-1, 10, -1, 10)
        self.SilderHbLayout.setSpacing(5)
        self.SilderHbLayout.setObjectName("SilderHbLayout")
        self.verticalLayout_3.addLayout(self.SilderHbLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CatSlider = QCatGrayDoubleSlider(self.SliderWidget)
        self.CatSlider.setMinimumSize(QtCore.QSize(0, 20))
        self.CatSlider.setObjectName("CatSlider")
        self.horizontalLayout_2.addWidget(self.CatSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CatVbSlider = QCatGrayDoubleSlider(self.SliderWidget)
        self.CatVbSlider.setMinimumSize(QtCore.QSize(20, 100))
        self.CatVbSlider.setMaximumSize(QtCore.QSize(20, 16777215))
        self.CatVbSlider.setObjectName("CatVbSlider")
        self.horizontalLayout_3.addWidget(self.CatVbSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.SliderWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        spacerItem2 = QtWidgets.QSpacerItem(125, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)

        self.retranslateUi(SliderTools)
        QtCore.QMetaObject.connectSlotsByName(SliderTools)

    def retranslateUi(self, SliderTools):
        _translate = QtCore.QCoreApplication.translate
        SliderTools.setWindowTitle(_translate("SliderTools", "Form"))
        self.Define.setText(_translate("SliderTools", "QSlider"))
from QCatGrayDoubleSlider import QCatGrayDoubleSlider
