#ifndef REP_CATSERIALREMOTE_SOURCE_H
#define REP_CATSERIALREMOTE_SOURCE_H

// This is an autogenerated file.
// Do not edit this file, any changes made will be lost the next time it is generated.

#include <QtCore/qobject.h>
#include <QtCore/qdatastream.h>
#include <QtCore/qvariant.h>
#include <QtCore/qmetatype.h>

#include <QtRemoteObjects/qremoteobjectnode.h>
#include <QtRemoteObjects/qremoteobjectsource.h>


class CatSerialRemoteSource : public QObject
{
    Q_OBJECT
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_TYPE, "CatSerialRemote")
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_SIGNATURE, "a49a4c182d6c6b83b001a2ed714aaa7b4aa6e13b")

public:
    explicit CatSerialRemoteSource(QObject *parent = nullptr) : QObject(parent)
    {
    }

public:
    ~CatSerialRemoteSource() override = default;


private:
    friend class QT_PREPEND_NAMESPACE(QRemoteObjectNode);
};


class CatSerialRemoteSimpleSource : public CatSerialRemoteSource
{
    Q_OBJECT

public:
    explicit CatSerialRemoteSimpleSource(QObject *parent = nullptr) : CatSerialRemoteSource(parent)
    {
    }

public:
    ~CatSerialRemoteSimpleSource() override = default;


private:
};


template <class ObjectType>
struct CatSerialRemoteSourceAPI : public SourceApiMap
{
    CatSerialRemoteSourceAPI(ObjectType *object, const QString &name = QLatin1String("CatSerialRemote"))
        : SourceApiMap(), m_name(name)
    {
        Q_UNUSED(object);
        m_enums[0] = 0;
        m_properties[0] = 0;
        m_signals[0] = 0;
        m_methods[0] = 0;
    }

    QString name() const override { return m_name; }
    QString typeName() const override { return QStringLiteral("CatSerialRemote"); }
    int enumCount() const override { return m_enums[0]; }
    int propertyCount() const override { return m_properties[0]; }
    int signalCount() const override { return m_signals[0]; }
    int methodCount() const override { return m_methods[0]; }
    int sourceEnumIndex(int index) const override
    {
        if (index < 0 || index >= m_enums[0])
            return -1;
        return m_enums[index+1];
    }
    int sourcePropertyIndex(int index) const override
    {
        if (index < 0 || index >= m_properties[0])
            return -1;
        return m_properties[index+1];
    }
    int sourceSignalIndex(int index) const override
    {
        if (index < 0 || index >= m_signals[0])
            return -1;
        return m_signals[index+1];
    }
    int sourceMethodIndex(int index) const override
    {
        if (index < 0 || index >= m_methods[0])
            return -1;
        return m_methods[index+1];
    }
    int signalParameterCount(int index) const override { Q_UNUSED(index); return -1; }
    int signalParameterType(int sigIndex, int paramIndex) const override
    { Q_UNUSED(sigIndex); Q_UNUSED(paramIndex); return -1; }
    int methodParameterCount(int index) const override { Q_UNUSED(index); return -1; }
    int methodParameterType(int methodIndex, int paramIndex) const override
    { Q_UNUSED(methodIndex); Q_UNUSED(paramIndex); return -1; }
    int propertyIndexFromSignal(int index) const override
    {
        Q_UNUSED(index);
        return -1;
    }
    int propertyRawIndexFromSignal(int index) const override
    {
        Q_UNUSED(index);
        return -1;
    }
    const QByteArray signalSignature(int index) const override
    {
        Q_UNUSED(index);
        return QByteArrayLiteral("");
    }
    QList<QByteArray> signalParameterNames(int index) const override
    {
        if (index < 0 || index >= m_signals[0])
            return QList<QByteArray>();
        return ObjectType::staticMetaObject.method(m_signals[index + 1]).parameterNames();
    }
    const QByteArray methodSignature(int index) const override
    {
        Q_UNUSED(index);
        return QByteArrayLiteral("");
    }
    QMetaMethod::MethodType methodType(int) const override
    {
        return QMetaMethod::Slot;
    }
    QList<QByteArray> methodParameterNames(int index) const override
    {
        if (index < 0 || index >= m_methods[0])
            return QList<QByteArray>();
        return ObjectType::staticMetaObject.method(m_methods[index + 1]).parameterNames();
    }
    const QByteArray typeName(int index) const override
    {
        Q_UNUSED(index);
        return QByteArrayLiteral("");
    }
    QByteArray objectSignature() const override { return QByteArray{"a49a4c182d6c6b83b001a2ed714aaa7b4aa6e13b"}; }

    int m_enums[1];
    int m_properties[1];
    int m_signals[1];
    int m_methods[1];
    const QString m_name;
};

QT_BEGIN_NAMESPACE
QT_END_NAMESPACE


#endif // REP_CATSERIALREMOTE_SOURCE_H
