# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/catgray/catgray/code/CatLearnQt/examples/QCatGrayWidgetExamples/CatQuickWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CatQuickWidget(object):
    def setupUi(self, CatQuickWidget):
        CatQuickWidget.setObjectName("CatQuickWidget")
        CatQuickWidget.resize(600, 462)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CatQuickWidget)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ToolWidget = QtWidgets.QWidget(CatQuickWidget)
        self.ToolWidget.setMinimumSize(QtCore.QSize(60, 0))
        self.ToolWidget.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ToolWidget.setObjectName("ToolWidget")
        self.horizontalLayout.addWidget(self.ToolWidget)
        self.ToolStackedWidget = QtWidgets.QStackedWidget(CatQuickWidget)
        self.ToolStackedWidget.setObjectName("ToolStackedWidget")
        self.horizontalLayout.addWidget(self.ToolStackedWidget)

        self.retranslateUi(CatQuickWidget)
        QtCore.QMetaObject.connectSlotsByName(CatQuickWidget)

    def retranslateUi(self, CatQuickWidget):
        _translate = QtCore.QCoreApplication.translate
        CatQuickWidget.setWindowTitle(_translate("CatQuickWidget", "Form"))
